name: Waka Readme

on:
  schedule:
    # Update setiap hari jam 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Bisa dijalankan manual juga

jobs:
  update-readme:
    name: Update README with WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update WakaTime stats in README
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
